baseURL = "https://murphe22.com"
languageCode = "en-us"
title = "Emily's Personal Website!"
theme = "anubis"
paginate = 4


disqusShortname = ""
googleAnalytics = ""

[author]
name = "Emily Murphy"

[params]
author = "Emily Murphy"
description = "Emily Murphy's Personal Website"
gtm_id = "G-X2SRPQFBT4"
gtm_ga = true
gtm_endpoint = "murphe22.com"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "light"
readMore = false
copyCodeButton = true
rssAsSocialIcon = false
enableEmoji = true

# utteranc.es support
utterancesRepo = ""  # mandatory

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4



[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/murphe22/"

[[params.social]]
id = "github"
url = "https://github.com/emurph1"

[[params.social]]
id = "twitter"
url = "https://github.com/emurph1"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Writeups"
identifier = "writeups"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Contact"
identifier = "contact"
url = "/contact/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true